#ifndef __KERNEL_CONF_H__
#define __KERNEL_CONF_H__

/* This file is auto-generated by CMake and scripts under conf/ */

#define KERNEL_BUILD_NAME               "tinyKern"
#define KERNEL_BUILD_VERSION            "0.0.1"
#define KERNEL_BUILD_TARGET             "AARCH64_QEMU"
#define KERNEL_BUILD_STYLE              "DEBUG"
#define KERNEL_SOURCE_VERSION           "tinykern-0040.20.70.2"

#endif /* __kernel_conf_h__ */